export enum requestActionTypes {
    AUTHED_GET_REQUEST = 'AUTHED_GET_REQUEST',
    AUTHED_POST_REQUEST = 'AUTHED_POST_REQUEST',
    AUTHED_DELETE_REQUEST = 'AUTHED_DELETE_REQUEST',
    UNAUTHED_GET_REQUEST = 'UNAUTHED_GET_REQUEST',
    UNAUTHED_POST_REQUEST = 'UNAUTHED_POST_REQUEST',
    AUTHED_PUT_REQUEST = 'AUTHED_PUT_REQUEST',
    REQUEST_COMPLETED = 'REQUEST_COMPLETED'
}

export const REQUEST_EXCEPTION = 'REQUEST_EXCEPTION'

